---
# See https://azure.microsoft.com/en-gb/documentation/articles/virtual-machines-linux-create-upload-generic/
#     https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-create-upload-generic#general-linux-installation-notes
#     http://withblue.ink/2015/12/22/preparing-a-red-hat-enterprise-linux-7-image-for-azure-using-virtualbox.html

- name: Disable root logins with password
  lineinfile: dest=/etc/ssh/sshd_config regexp='^(#\s*)?PermitRootLogin' line='PermitRootLogin without-password' state=present

- name: Disable Local Root Access
  command: passwd -l root
  failed_when: "'passwd: Success' not in last.stdout"
  register: last

- command: sed -n 's/GRUB_CMDLINE_LINUX="\(.*\)"/\1/p' /etc/default/grub
  register: grub_cmdline
  changed_when: false

- name: Log boot to the console
  lineinfile: dest=/etc/default/grub regexp='^{{item.key}}' line='{{item.key}}="{{grub_cmdline.stdout.split() | union(item.add) | difference(item.del) | join(" ")}}"' owner=root group=root mode=0644
  with_items:
    - key: GRUB_CMDLINE_LINUX
      add: ['console=ttyS0', 'earlyprintk=ttyS0', 'rootdelay=300', 'net.ifnames=0']
      del: ['rhgb', 'quiet', 'crashkernel=auto']
  register: grub

- name: Regenerate grub configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub.changed

- name: Add Hyper-V modules to initramfs
  template: dest=/etc/dracut.conf.d/hyperv.conf src=dracut_hyperv.conf.j2 owner=root group=root mode=0644
  register: dracut

- name: Rebuild initramfs
  command: dracut -f
  when: dracut.changed

- name: Add repository for Azure agent
  yum_repository: name=openlogic description="Openlogic's Azure agent'" baseurl=http://olcentgbl.trafficmanager.net/openlogic/{{ansible_distribution_version}}/openlogic/x86_64/ gpgcheck=yes gpgkey=http://olcentgbl.trafficmanager.net/openlogic/{{ansible_distribution_version}}/openlogic/x86_64/OpenLogic-GPG-KEY enabled=yes state=present owner=root group=root mode=0644

- name: Install Azure agent and dependencies
  yum:
    name:
      - python
      - python-pyasn1
      - WALinuxAgent

- name: Configure swap in Azure agent
  lineinfile: dest=/etc/waagent.conf regexp='^(#\s*)?{{item.key}}' line='{{item.key}}={{item.value}}' owner=root group=root mode=0644
  with_dict:
    ResourceDisk.Format: 'y'
    ResourceDisk.Filesystem: ext4
    ResourceDisk.MountPoint: /mnt/resource
    ResourceDisk.EnableSwap: 'y'
    ResourceDisk.SwapSizeMB: 1048

- name: Enable Azure agent
  service: name=waagent state=started enabled=yes

- name: Deprovision machine (final step)
  command: waagent -force -deprovision
