---
# Ref: https://cloud.google.com/compute/docs/tutorials/building-images

- import_tasks: tasks/grub.yml
  vars:
    grub_add: ['console=ttyS0,38400n8']
    grub_del: ['rhgb', 'quiet', 'crashkernel=auto']

- name: Drop Google Cloud Compute repo
  template: dest=/etc/yum.repos.d/google-cloud.repo src=templates/google-cloud.repo.j2 owner=root group=root mode=0644

- name: Install packages
  yum:
    name:
      - python
      - google-compute-engine
      - google-compute-engine-init
      - google-config

- name: Secure sshd config
  lineinfile: dest=/etc/ssh/sshd_config regexp='^(#\s*)?{{item.key}}' line='{{item.key}} {{item.value}}' state=present owner=root group=root mode=0644
  with_dict:
    PasswordAuthentication: 'no'
    PermitRootLogin: 'without-password'
    PermitTunnel: 'no'
    AllowTcpForwarding: 'yes'
    X11Forwarding: 'no'
    ClientAliveInterval: 420

- name: Secure ssh config
  lineinfile: dest=/etc/ssh/ssh_config regexp='^(#\s*)?{{item.key}}' line='{{item.key}} {{item.value}}' state=present owner=root group=root mode=0644
  with_dict:
    Host: '*'
    Protocol: 2
    ForwardAgent: 'no'
    ForwardX11: 'no'
    HostbasedAuthentication: 'no'
    StrictHostKeyChecking: 'no'
    Ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc
    Tunnel: 'no'
    ServerAliveInterval: 420

- name: Recommended kernel parameters
  template: dest=/etc/sysctl.d/12-gcp-recommended.conf src=gcp-recommended-sysctl.conf.j2 owner=root group=root mode=0644

- name: Configure network default IPv4 interface
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-{{ansible_default_ipv4.interface}} regexp='^(#\s*)?{{item.key}}=' line='{{item.key}}={{item.value}}' state=present owner=root group=root mode=0644
  with_dict:
    IPV6INIT: 'no'
    MTU: 1460
