---
# See http://docs.openstack.org/image-guide

- name: Install ACPI service
  yum: name=acpid

- name: Start ACPI service
  service: name=acpid enabled=yes state=started

- name: Disable the zerconf route
  lineinfile: dest=/etc/sysconfig/network regexp="^NOZEROCONF" line="NOZEROCONF=yes" owner=root group=root mode=0644 backup=yes

- import_tasks: tasks/grub.yml
  vars:
    grub_add: ['console=tty0', 'console=ttyS0,115200n8']
    grub_del: ['rhgb', 'quiet']

- import_tasks: tasks/cloud_init.yml
