---
- name: Install vmware tools
  yum: name=open-vm-tools

- name: Start vmtoolsd service
  service: name=vmtoolsd state=started enabled=yes

- import_tasks: tasks/grub.yml
  vars:
    grub_add: ['ds=nocloud-net']

- import_tasks: tasks/cloud_init.yml
