---
- name: Install vmware tools
  yum: name=open-vm-tools

- name: Start vmtoolsd service
  service: name=vmtoolsd state=started enabled=yes

- import_tasks: tasks/cloud_init.yml
  vars:
    cloud_init_local_config:
      disable_root: 'False'
      ssh_pwauth: unchanged

- name: Grow LVM partition with cloud-init
  template: dest=/etc/cloud/cloud.cfg.d/01_growlvm.cfg src=templates/cloud_init_growlvm.cfg.j2 mode=0644 owner=root group=root
  vars:
    grow_pv: /dev/sda2

- name: Create directory for cloud-init per-boot scripts
  file: path=/var/lib/cloud/scripts/per-boot state=directory owner=root mode=0755

- name: Resize LVM partition with cloud-init
  template: dest=/var/lib/cloud/scripts/per-boot/resize-lvm.sh src=templates/cloud_init_resize.sh.j2 mode=0755 owner=root group=root
  vars:
    grow_pv: /dev/sda2
    grow_vg: rootvg
    grow_lv: rootvol
